<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>/var/www/wsldebian/wsl_workspace @ Environment.php</title>
    <link rel="icon" type="image/ico" href="favicon.ico">
    <link rel="shortcut icon" type="image/ico" href="favicon.ico">
    <link rel="stylesheet" href="https://unpkg.com/chota@latest">
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/notes.css" rel="stylesheet">
    <link href="assets/css/lightslider.css" rel="stylesheet">
</head>

<body>
    <div id="pagewidth" class="container">
        <!-- #HEADER -->
        <section id="header">
            <h1 class="bg-dark text-light text-end pe-3 h1">Convert System Path to HTTP URL</h1>
        </section>
        <section>
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="h5">New Approach</h5>
                            <div>
                                <br>path[0]: var<br>path[1]: www<br>path[2]: wsldebian<br>path[3]: wsl_workspace<br>
                                Resulting URL buildByComp: <a href="https://wsldebian/wsl_workspace" target="_blank">https://wsldebian/wsl_workspace</a><br>
                                Resulting URL concatThis: <a href="https://wsldebian/wsl_workspace" target="_blank">https://wsldebian/wsl_workspace</a><br>
                                Resulting URL concatSwitch: <a href="https://" target="_blank">https://</a>
                            </div>
                            <div id="image_look">
                                <dl>
                                    <dt>Screenshot: </dt>
                                    <dd>Could go here if you want</dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5>Dynamic Drop</h5>
                            <div id="demos" class="ol-blue">Mod with JavaScript</div>
                            <p class="attention">Leave Subdomain at [none] if none exists.</p>
                            <form id="fixtheurl" class="ol-green">
                                <label for="prefix" class="ol-grey">subdomain</label>
                                <select id="prefix">
                                    <option value="">[none]</option>
                                    <option value="other">other</option>
                                    <option value="atheat">atheat</option>
                                    <option value="atflux">atflux</option>
                                    <option value="laravel">laravel</option>
                                    <option value="python">python</option>
                                    <option value="mx21">mx21</option>
                                </select>

                                <label for="prefix">TLD / server_name</label>
                                <div id="infospace">(prefix)
                                    <select id="suffix">
                                        <option value="mxuni">mxuni</option>
                                        <option value="wsldebian">wsldebian</option>
                                        <option value="mxlinux-21">bunsen</option>
                                    </select>
                                </div>
                                <input id="newItemInput" />
                                <button type="button" onclick="appendSelectedValue()">Append Selected Value</button>
                                <button type="button" onclick="updateAppendedData()">Update Appended Data</button>
                            </form>
                            <div id="appendedData"></div>
                            <div id="oldAppendedData"></div>
                            <h5 class="h5">Process a Path</h5>
                            <div id="quickentry">
                                <form action="/wsl_workspace/public/index.phtml" id="p2u2top" method="GET">
                                    <label for="path2url" class="xhidden">_GET['path2url']:</label>
                                    <input type="text" name="path2url" id="path2url" value="/var/www/wsldebian/wsl_workspace">
                                    <button class="btn btn
