<div class="card ol-red">
<h3>Twerkin Path</h3>
<div id="demos" class="ol-blue">
<p class="attention">Leave Subdomain at [none] if none exists.</p>
    <form id="fixtheurl" class="ol-green">
        <label for="prefix" class="ol-grey">subdomain</label>
        <div id="spaceinfo">
        <select id="prefix">
            <option value="">[none]</option>
            <option value="support">support</option>
            <option value="blog">blog</option>
            <option value="forum">forum</option>
            <option value="help">help</option>
            <option value="doc">doc</option>
            <option value="app">app</option>
        </select>
        </div>
        <label for="prefix">server_name</label>
		<div id="infospace">
        <select id="suffix">
            <option value="">[none]</option>
            <option value="localhost">localhost</option>
            <option value="127.0.0.1">127.0.0.1</option>
            <option value="example.org">example.org</option>
            <option value="github.com">github.com</option>
            <option value="vivaldi.net">vivaldi.net</option>
        </select>
		</div>
        <input type="text" id="newItemInput"  placeholder="Twerkin path here">
        <button type="button" onclick="updateAppendedData()">Update [sub]Domain</button>
        <button type="button" onclick="appendSelectedValue()">Add Path (x2 for link)</button>

    </form>
    <div id="appendedData"></div>
    <div id="oldAppendedData"></div>
</div>
</div> <!-- card.ol-red -->
<div clas="card ol-blue">
 <h3 class="h3">Raw Path:</h3> 
                        <div id="quickentry">
                            <p>Try a new path. Make new links</p>
                            <form action="<?= $_SERVER['PHP_SELF']; ?>" id="p2u2top" method="GET">
                                <label for="path2url" class="xhidden">_GET['path2url']:</label>
                                <input type="text" name="path2url" id="path2url" value="<?php print $enterpathhere; ?>">
                                <button class="btn btn-primary" type="submit" name="submit">Make New Link</button>
                            </form>
                        </div>
</div>
<script src="assets/js/dynamicdrop.js"></script> 