<div class="container">
    <div class="row">
    <div class="col">
                <div class="card">
                        <div class="card-body">
                            <h2>Processing Summary:</h2>
                            <div>
                                <!-- new approach -->
                                <dl>
                    <dt class="pointer">Path <span class="thin">(three different ways)</span> <span class="normal blue pointer" id="show_g01"
                            onclick="swap_text('show_g01','glossary_01') "> [details...]</span>
                    </dt>
                    <dd id="glossary_01" class="displaynone">
                         <p>Using regular expressions and other syntax, the URL components which make up the path
                                    are separated and stored in an array, "path[]". </p>
                                <p><code>path[]</code> is derived from <code
                                        class="php">$Eval->test_location($enterpathhere)['pb'];</code></p>
                                <ul>
                                    <li><code>buldByComp</code> uses _SERVER[], path[], to build the resulting HTTP url.
                                    </li>
                                    <li><code>concatThis</code> uses that info but first removes some standard known
                                        paths in attempt to achive a more likely correct URL, and tends to be the most reliable of the three results.</li>
                                    <li><code>concatSwitch</code> employs the use of a switch case logic. This is usually garbage for some reason. All in the spirit of playing with code.</li>
                                </ul>
                                <?php
        $common_paths=[
            '\/opt\/lampp\/htdocs',
            '\/var\/www\/html',
            '\/var\/www\/htdocs',
            '\/var\/www\/public_html',
            '\/var\/www\/htdocs\/public_html',
            '\/var\/www\/wwwroot',
            '\/home\/admin\/web'
        ];
// $trimmed_new_url = str_ireplace('/var/www/' . $contructNewMethod['_dynamichost'], '', $contructNewMethod['new_url_concat']);
foreach($common_paths as $cpathKey => $cpathVal){
    if(preg_match($cpathVal,$contructNewMethod['new_url_concat'])){
    $trimmed_new_url = str_ireplace($cpathVal, '', $contructNewMethod['new_url_concat']);
        
    break;
    }
    
}

$buildByComp = $_SERVER['REQUEST_SCHEME'] . '://' . $contructNewMethod['_dynamichost'] . '/' . ltrim($trimmed_new_url, '/');
$concatThis = $_SERVER['REQUEST_SCHEME'] . '://'. $contructNewMethod['_dynamichost'] .'/';
$concatSwitch = $_SERVER['REQUEST_SCHEME'] . '://'. $contructNewMethod['_dynamichost'];
foreach ($P2u2->path_comps['matches'] as $mKey => $mVal) {
    echo '<br>path[' . $mKey . ']: ' . $mVal;
    if ($mVal != 'var' && $mVal != 'www' && $mVal != 'admin' && $mVal != 'home' && $mVal != 'web') {
        $mVal =  str_ireplace('public_html','',$mVal);
        $mVal = str_ireplace('//','/',$mVal);
        $concatThis .= ltrim($mVal, '/') . '/';
        // $concatThis = str_ireplace($_SERVER['SERVER_NAME'],'/',$concatThis);
    }
}

$process_location = $Eval->test_location($enterpathhere)['pb'];

foreach ($process_location as $mKey => $mVal) {
    echo '<br>path[' . $mKey . ']: ' . $mVal;
    $concatSwitch .= str_ireplace('/', '', $mVal) . '/';
}
?>
</dd>
</dl>
<?php
// $concatThis = str_ireplace('//','/',$concatThis);
echo '<dl id="resulting_url_anchors">';
echo '<dt>buildByComp (dynamic hostname)</dt><dd><a href="' . $buildByComp . '" target="_blank">' . $buildByComp . '</a></dd>';
echo '<dt>concatThis</dt>
    <dd><a id="concatThisAnchor" href="'.rtrim($concatThis,'/').'" target="_blank">' . rtrim($concatThis, '/') . '</a></dd>';

    echo '<dt>concatSwitch</dt><dd><a href="' . $concatSwitch . '" target="_blank">' . $concatSwitch . '</a></dd></dl>';
/*  echo '<h4>buildUrl vals:</h4>';
                       if(is_array($buildUrl)){
                       foreach($buildUrl as $bKey => $bVal) {
                        echo '<br>bVal['.$bKey.']: '.$bVal ;
                       }
                    } */

?>
                            </div>
                        </div>
</div>
    </div><!-- col -->

    <div class="col">
<h2>Try fix</h2>
<div clas="card ol-red">
                <p>Change the path and submit:</p>
 <h3 class="h3">Raw Path Used:</h3> 
    <div clas="ol-blue">
        <div id="quickentry">

            <form id="p2u2top" method="GET">
                <label for="path2url" class="hidden">_GET['path2url']:</label>
                <input type="text" name="path2url" id="path2url" value="<?php print $enterpathhere; ?>">
                <button class="btn btn-primary" type="submit" name="submit">Submit path</button>
            </form>
        </div>
    </div>
</div>
        </div>
    </div><!-- row -->
    <div class="row">
<div class="col">
<div class="card ol-red">
<h3>Twerkin Path</h3>
<div id="demos" class="ol-blue">
<p class="details attention">Leave Subdomain at [none] if none exists.</p>
    <form id="fixtheurl" class="ol-green">
        <label for="prefix" class="ol-grey">subdomain</label>
        <div id="spaceinfo">
        <select id="prefix">
            <option value="">[none]</option>
            <option value="support">support</option>
            <option value="blog">blog</option>
            <option value="forum">forum</option>
            <option value="help">help</option>
            <option value="doc">doc</option>
            <option value="app">app</option>
        </select>
        </div>
        <label for="prefix">server_name</label>
		<div id="infospace">
        <select id="suffix">
            <option value="">[none]</option>
            <option value="localhost" selected>localhost</option>
            <option value="127.0.0.1">127.0.0.1</option>
            <option value="example.org">example.org</option>
            <option value="github.com">github.com</option>
            <option value="vivaldi.net">vivaldi.net</option>
        </select>
		</div>
        <input type="text" id="newItemInput"  placeholder="Twerkin path here">
        <button type="button" onclick="updateAppendedData()">Update [sub]Domain</button>
        <button type="button" onclick="appendSelectedValue()">Add Path (x2 for link)</button>

    </form>
    <div id="appendedData"></div>
    <div id="oldAppendedData"></div>
</div>
</div> <!-- card.ol-red -->
    </div>
        </div>
<script src="assets/js/dynamicdrop.js"></script> 