<!-- :before Twerkin.form.phtml -->
<div id="twerkin-division" class="w-50 ma ph2 pv1 v-mid-l bg-light-green fl bg-animate">    
<h3>Twerkin Path</h3>
<div id="demos" class="outline-l">
<p class="f6">Leave Subdomain at [none] if none exists.</p>
<form id="fixtheurl" class="ol-green">
<label for="prefix" class="ol-grey">subdomain</label>
<div id="spaceinfo">
<select id="prefix">
<option value="">[none]</option>
<option value="support">support</option>
<option value="blog">blog</option>
<option value="forum">forum</option>
<option value="help">help</option>
<option value="doc">doc</option>
<option value="app">app</option>
</select>
</div>
<label for="prefix">server_name</label>
<div id="infospace">
<select id="suffix">
<option value="">[none]</option>
<option value="localhost" selected>localhost</option>
<option value="127.0.0.1">127.0.0.1</option>
<option value="example.org">example.org</option>
<option value="github.com">github.com</option>
<option value="vivaldi.net">vivaldi.net</option>
</select>
</div>
<input type="text" id="newItemInput"  placeholder="Twerkin path here">
<button type="button" onclick="updateAppendedData()">Update [sub]Domain</button>
<button type="button" onclick="appendSelectedValue()">Add Path (x2 for link)</button>

</form>
<div id="appendedData"></div>
<div id="oldAppendedData"></div>
        </div><!-- :after Twerkin.form.phtml -->
</div>
